api:
  name: "api"
  frontend_port: 5002
  container_port: 5000
  aggregate_queue: "default"
  inference_queue: "default"
celery:
  name: "celery"
  frontend_port: 5001
  container_port: 5000
postgres:
  user: "tagup"
  pw: "tagup"
  port: 5432
  db: "postgres"
rabbitmq:
  queue_port: 5672
  mgmt_port: 15672
  user: "tagup"
  pw: "tagup"
redis:
  port: 6379

