apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.celery.name }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.celery.name }}"
  template:
    metadata:
      labels:
        app: "{{ .Values.celery.name }}"
    spec:
      containers:
      - image: "ghcr.io/tagup/devops-interview:latest"
        name: "{{ .Values.celery.name }}"
        command:
        - /app/entrypoints/docker-entrypoint.sh
        args:
        - celery
        env:
          - name: POSTGRES_USER
            value: "{{ .Values.postgres.user }}"
          - name: POSTGRES_PASSWORD
            value: "{{ .Values.postgres.pw }}"
          - name: DATABASE_URI
            value: "postgresql+psycopg://{{ .Values.postgres.user }}:{{ .Values.postgres.pw }}@postgres:{{ .Values.postgres.port }}/postgres"
          - name: REDIS_URI
            value: "redis://redis:{{ .Values.redis.port }}/0"
          - name: CELERY_BROKER_URL
            value: "amqp://{{ .Values.rabbitmq.user }}:{{ .Values.rabbitmq.pw }}@rabbitmq:{{ .Values.rabbitmq.queue_port }}/"
        resources:
          requests:
            memory: "512Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "100m"

